import {
  User,
  Customer,
  Vessel,
  Port,
  Zone,
  FixTariff,
  ExpensesItem,
  JobCall,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Budi Santoso',
    email: 'admin@maritimport.id',
    role: 'ADMIN',
    department: 'IT & System Admin',
    branch: 'JKT',
    status: 'ACTIVE',
    phone: '+62 811-987-1001',
    username: 'admin',
    password: 'admin123',
    position: 'System Administrator',
  },
  {
    id: 'USR-002',
    name: 'Sarah Wijaya',
    email: 'sarah.sales@maritimport.id',
    role: 'SALES',
    department: 'Commercial & Sales',
    branch: 'JKT',
    status: 'ACTIVE',
    phone: '+62 812-456-2002',
    username: 'sales',
    password: 'sales123',
    position: 'Sales Executive',
  },
  {
    id: 'USR-003',
    name: 'Capt. Hendra Pratama',
    email: 'hendra.ops@maritimport.id',
    role: 'MANAGER_OPS',
    department: 'Marine Operations',
    branch: 'JKT',
    status: 'ACTIVE',
    phone: '+62 813-789-3003',
    username: 'manager',
    password: 'manager123',
    position: 'Manager Operations',
  },
  {
    id: 'USR-004',
    name: 'Rizky Kurniawan',
    email: 'rizky.fda@maritimport.id',
    role: 'FDA',
    department: 'Disbursement & Husbandry (FDA)',
    branch: 'JKT',
    status: 'ACTIVE',
    phone: '+62 815-332-4004',
    username: 'fda',
    password: 'fda123',
    position: 'FDA Officer',
  },
  {
    id: 'USR-005',
    name: 'Dewi Lestari, SE, Ak',
    email: 'dewi.finance@maritimport.id',
    role: 'FINANCE',
    department: 'Finance & Accounting',
    branch: 'JKT',
    status: 'ACTIVE',
    phone: '+62 818-654-5005',
    username: 'finance',
    password: 'finance123',
    position: 'Finance & Accounting',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-001',
    code: 'GLO-01',
    companyName: 'Global Maritime Lines Pte Ltd',
    country: 'Singapore',
    type: 'PRINCIPAL',
    contactPerson: 'Capt. Michael Chang',
    email: 'agency.sg@glo-maritime.com',
    phone: '+65 6789 1234',
    address: '78 Shenton Way #18-01, Singapore 079120',
    creditTermDays: 30,
  },
  {
    id: 'CUST-002',
    code: 'COS-02',
    companyName: 'Cosco Shipping Energy Transportation',
    country: 'Hong Kong',
    type: 'PRINCIPAL',
    contactPerson: 'Ms. Lin Wei',
    email: 'ops.asia@cosco-energy.hk',
    phone: '+852 2890 5541',
    address: '48/F, COSCO Tower, 183 Queen\'s Road Central, Hong Kong',
    creditTermDays: 45,
  },
  {
    id: 'CUST-003',
    code: 'ADR-03',
    companyName: 'PT Adaro Energy Logistik',
    country: 'Indonesia',
    type: 'CHARTERER',
    contactPerson: 'Bambang Sudibyo',
    email: 'shipping@adaro-logistics.co.id',
    phone: '+62 21 521 1265',
    address: 'Menara Karya Lt. 22, Jl. H.R. Rasuna Said Blok X-5 Kav. 1-2, Jakarta',
    creditTermDays: 14,
  },
  {
    id: 'CUST-004',
    code: 'MAER-04',
    companyName: 'A.P. Moller - Maersk Agency',
    country: 'Denmark',
    type: 'SHIPOWNER',
    contactPerson: 'Niels Andersen',
    email: 'hub.ops@maersk.com',
    phone: '+45 3363 3363',
    address: 'Esplanaden 50, 1098 Copenhagen K, Denmark',
    creditTermDays: 30,
  },
];

export const INITIAL_VESSELS: Vessel[] = [
  {
    id: 'VES-001',
    name: 'MV OCEAN PIONEER',
    imoNumber: '9456782',
    callSign: '9V8921',
    flag: 'Singapore',
    vesselType: 'BULK CARRIER',
    grt: 32500,
    nrt: 18200,
    dwt: 57000,
    loa: 189.9,
    beam: 32.26,
    yearBuilt: 2018,
  },
  {
    id: 'VES-002',
    name: 'MT MERDEKA SAMUDRA',
    imoNumber: '9678124',
    callSign: 'YDF882',
    flag: 'Indonesia',
    vesselType: 'OIL TANKER',
    grt: 64200,
    nrt: 35100,
    dwt: 105000,
    loa: 243.8,
    beam: 42.0,
    yearBuilt: 2021,
  },
  {
    id: 'VES-003',
    name: 'MV PACIFIC HORIZON',
    imoNumber: '9345091',
    callSign: 'V2BQ8',
    flag: 'Panama',
    vesselType: 'CONTAINER',
    grt: 28400,
    nrt: 14800,
    dwt: 38200,
    loa: 182.5,
    beam: 29.8,
    yearBuilt: 2016,
  },
  {
    id: 'VES-004',
    name: 'BG SAMUDRA PERKASA 300',
    imoNumber: '8991203',
    callSign: 'PO991',
    flag: 'Indonesia',
    vesselType: 'TUG & BARGE',
    grt: 3800,
    nrt: 1900,
    dwt: 8500,
    loa: 91.5,
    beam: 24.4,
    yearBuilt: 2020,
  },
];

export const INITIAL_PORTS: Port[] = [
  {
    id: 'PRT-001',
    code: 'BTH',
    name: 'Batu Ampar, Batam',
    country: 'Indonesia',
    unlocode: 'IDBTH',
    channelDepthMeters: 14.5,
    tideRestriction: 'Max 3.2m tidal range, daylight berthing for >180m LOA',
    operatingHours: '24/7 with advance pilot notice',
  },
  {
    id: 'PRT-002',
    code: 'TPP',
    name: 'Tanjung Priok, Jakarta',
    country: 'Indonesia',
    unlocode: 'IDTPP',
    channelDepthMeters: 16.0,
    tideRestriction: 'Tidal range 1.2m, 24/7 navigation',
    operatingHours: '24/7 standard port operation',
  },
  {
    id: 'PRT-003',
    code: 'SUB',
    name: 'Tanjung Perak, Surabaya',
    country: 'Indonesia',
    unlocode: 'IDSUB',
    channelDepthMeters: 13.0,
    tideRestriction: 'APBS channel depth 10.5m LWS',
    operatingHours: '24/7',
  },
  {
    id: 'PRT-004',
    code: 'BPN',
    name: 'Semayang / Kariangau, Balikpapan',
    country: 'Indonesia',
    unlocode: 'IDBPN',
    channelDepthMeters: 15.2,
    tideRestriction: 'Tidal window for tankers draft >12m',
    operatingHours: '24/7',
  },
];

export const INITIAL_ZONES: Zone[] = [
  {
    id: 'ZON-001',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    zoneCode: 'BTH-B01',
    zoneName: 'Berth 101 Bulk & General',
    type: 'BERTH',
    maxDraftMeters: 12.8,
    description: 'Primary commercial jetty with 2 mobile harbor cranes',
  },
  {
    id: 'ZON-002',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    zoneCode: 'BTH-ANC-01',
    zoneName: 'Outer Anchorage Batu Ampar (Nipa/Batam road)',
    type: 'ANCHORAGE',
    maxDraftMeters: 22.0,
    description: 'Designated deep water awaiting area and bunker point',
  },
  {
    id: 'ZON-003',
    portId: 'PRT-002',
    portName: 'Tanjung Priok, Jakarta',
    zoneCode: 'TPP-CT1',
    zoneName: 'Jakarta International Container Terminal (JICT 1)',
    type: 'BERTH',
    maxDraftMeters: 14.5,
    description: 'Deep container quay with post-panamax STS cranes',
  },
  {
    id: 'ZON-004',
    portId: 'PRT-004',
    portName: 'Semayang / Kariangau, Balikpapan',
    zoneCode: 'BPN-STS',
    zoneName: 'Balikpapan Bay Ship-to-Ship Transfer Point #2',
    type: 'STS',
    maxDraftMeters: 18.5,
    description: 'Offshore oil and gas transshipment zone',
  },
];

export const INITIAL_FIX_TARIFFS: FixTariff[] = [
  {
    id: 'TAR-001',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    costCategory: 'PILOTAGE_TOWAGE',
    serviceCode: 'PILOT-INOUT',
    serviceName: 'Compulsory Harbor Pilotage (In/Outbound)',
    calculationBasis: 'PER_GRT',
    currency: 'USD',
    rate: 0.038,
    minCharge: 450,
    description: 'State harbor pilot onboard from pilot station to berth',
  },
  {
    id: 'TAR-002',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    costCategory: 'PILOTAGE_TOWAGE',
    serviceCode: 'TUG-ASSIST',
    serviceName: 'Tugboat Assistance (2 x 3500 HP Tugs)',
    calculationBasis: 'PER_HOUR',
    currency: 'USD',
    rate: 420,
    minCharge: 840,
    description: 'Mandatory berthing/unberthing escort tugs',
  },
  {
    id: 'TAR-003',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    costCategory: 'BERTHING',
    serviceCode: 'BERTH-DUES',
    serviceName: 'Quay & Berthing Dues (Pelindo Tariff)',
    calculationBasis: 'PER_GRT',
    currency: 'IDR',
    rate: 165,
    minCharge: 2500000,
    description: 'Per GRT per 24-hour period docked at pier',
  },
  {
    id: 'TAR-004',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    costCategory: 'PORT_DUES',
    serviceCode: 'LIGHT-DUES',
    serviceName: 'Directorate General Sea Transportation Light Dues (Disnav)',
    calculationBasis: 'PER_GRT',
    currency: 'IDR',
    rate: 95,
    minCharge: 1500000,
    description: 'Valid for 30 calendar days across Indonesian navigation channels',
  },
  {
    id: 'TAR-005',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    costCategory: 'AGENCY_FEE',
    serviceCode: 'AGENCY-FEE',
    serviceName: 'Standard Port Agency Attendance Fee',
    calculationBasis: 'LUMP_SUM',
    currency: 'USD',
    rate: 1850,
    minCharge: 1850,
    description: 'Full agency handling up to 4 days port stay',
  },
];

export const INITIAL_EXPENSES_ITEMS: ExpensesItem[] = [
  {
    id: 'EXP-001',
    code: 'EXP-PLT',
    category: 'PILOTAGE_TOWAGE',
    name: 'Government Pilotage & Tug Services',
    defaultCurrency: 'USD',
    standardCostBuy: 1800,
    standardCostSell: 2150,
    preferredVendor: 'PT Pelabuhan Indonesia (Pelindo)',
  },
  {
    id: 'EXP-002',
    code: 'EXP-BRT',
    category: 'BERTHING',
    name: 'Berthage / Wharfage Fee (48 hrs)',
    defaultCurrency: 'IDR',
    standardCostBuy: 14500000,
    standardCostSell: 16800000,
    preferredVendor: 'Pelindo Batam Regional',
  },
  {
    id: 'EXP-003',
    code: 'EXP-MOOR',
    category: 'BERTHING',
    name: 'Mooring & Unmooring Gang Boat',
    defaultCurrency: 'IDR',
    standardCostBuy: 3200000,
    standardCostSell: 4200000,
    preferredVendor: 'Batam Line Boat Services',
  },
  {
    id: 'EXP-004',
    code: 'EXP-CREW',
    category: 'CREW_CHANGE',
    name: 'Crew Sign-On / Sign-Off Immigration Handling & OKTB',
    defaultCurrency: 'USD',
    standardCostBuy: 450,
    standardCostSell: 650,
    preferredVendor: 'Kantor Imigrasi Kelas I TPI Batam',
  },
  {
    id: 'EXP-005',
    code: 'EXP-TRAN',
    category: 'LOGISTICS_SUPPLIES',
    name: 'Airport Transfer & Fast Launch Boat to Anchorage',
    defaultCurrency: 'IDR',
    standardCostBuy: 4500000,
    standardCostSell: 6000000,
    preferredVendor: 'Citra Samudra Launch Logistics',
  },
  {
    id: 'EXP-006',
    code: 'EXP-GRB',
    category: 'PORT_DUES',
    name: 'Garbage & Marpol Sludge Disposal Certificate',
    defaultCurrency: 'USD',
    standardCostBuy: 380,
    standardCostSell: 520,
    preferredVendor: 'Green Port Marine Waste Services',
  },
  {
    id: 'EXP-007',
    code: 'EXP-WAT',
    category: 'LOGISTICS_SUPPLIES',
    name: 'Fresh Water Bunkering (150 MT via barge)',
    defaultCurrency: 'USD',
    standardCostBuy: 1650,
    standardCostSell: 2100,
    preferredVendor: 'Tirta Bahari Fresh Water Supply',
  },
  {
    id: 'EXP-008',
    code: 'EXP-CIQP',
    category: 'IMMIGRATION_CUSTOMS',
    name: 'CIQP Formalities & Health Quarantine Port Clearance',
    defaultCurrency: 'IDR',
    standardCostBuy: 2800000,
    standardCostSell: 3800000,
    preferredVendor: 'Balai Kekarantinaan Kesehatan Batam',
  },
  {
    id: 'EXP-009',
    code: 'EXP-AGCY',
    category: 'AGENCY_FEE',
    name: 'General Husbandry & Port Agency Fee',
    defaultCurrency: 'USD',
    standardCostBuy: 1200,
    standardCostSell: 1950,
    preferredVendor: 'MaritimPort Agency Internal',
  },
];

// Pre-seeded complete Job Call with full relational tree for VC-2026-0098 as specified in prompt
export const INITIAL_JOB_CALLS: JobCall[] = [
  {
    jobId: 'VC-2026-0098',
    vesselId: 'VES-001',
    vesselName: 'MV OCEAN PIONEER',
    portId: 'PRT-001',
    portName: 'Batu Ampar, Batam',
    customerId: 'CUST-001',
    customerName: 'Global Maritime Lines Pte Ltd',
    currency: 'USD',
    exchangeRateUSDToIDR: 15800,
    eta: '2026-09-02T08:00',
    etd: '2026-09-05T18:00',
    purposeOfCall: 'CARGO_DISCHARGE',
    currentStage: 'ACTUAL_COST',
    status: 'IN_PROGRESS',
    createdAt: '2026-08-26T10:00:00Z',
    updatedAt: '2026-09-03T07:15:00Z',

    // 1. Inquiry
    inquiry: {
      inquiryNo: 'INQ-2026-0182',
      date: '2026-08-26',
      cargoDetails: 'Discharge 42,500 MT of Steam Coal from Samarinda Anchorage',
      estimatedDays: 3.5,
      specialRequirements: 'Requires 4 crew sign-offs (Filipino/Indian) with connecting flights to SIN/MNL. Priority pilotage requested.',
      status: 'CONVERTED',
      createdBy: 'Sarah Wijaya (SALES)',
    },

    // 2. Quotation (EPDA, PDA, Crew Change)
    quotation: {
      epda: {
        quoteNo: 'EPDA-2026-0098-IDR-USD',
        date: '2026-08-27',
        currency: 'USD',
        totalBuyRate: 8250,
        totalSellRate: 10890,
        marginAmount: 2640,
        marginPercentage: 24.2,
        status: 'APPROVED',
        items: [
          {
            id: 'ITM-EPDA-1',
            expenseItemId: 'EXP-001',
            name: 'Harbor Pilotage & Tug Services (In & Out)',
            category: 'PILOTAGE_TOWAGE',
            basis: 'GRT calculation (32,500 GRT)',
            quantity: 2,
            unitBuyRate: 1800,
            unitSellRate: 2350,
            totalBuyRate: 3600,
            totalSellRate: 4700,
            currency: 'USD',
            remarks: 'BUY rate Pelindo concession tariff',
          },
          {
            id: 'ITM-EPDA-2',
            expenseItemId: 'EXP-002',
            name: 'Wharfage & Berthing Dues (Pelindo Batam)',
            category: 'BERTHING',
            basis: '4 days stay at Berth 101',
            quantity: 4,
            unitBuyRate: 230,
            unitSellRate: 310,
            totalBuyRate: 920,
            totalSellRate: 1240,
            currency: 'USD',
            remarks: 'Converted at 15,800 IDR/USD',
          },
          {
            id: 'ITM-EPDA-3',
            expenseItemId: 'EXP-003',
            name: 'Line Mooring & Unmooring Gang',
            category: 'BERTHING',
            basis: '2 operations',
            quantity: 2,
            unitBuyRate: 105,
            unitSellRate: 150,
            totalBuyRate: 210,
            totalSellRate: 300,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-4',
            expenseItemId: 'EXP-008',
            name: 'CIQP Formalities & Health Quarantine Clearance',
            category: 'IMMIGRATION_CUSTOMS',
            basis: 'Lump sum vessel call clearance',
            quantity: 1,
            unitBuyRate: 180,
            unitSellRate: 280,
            totalBuyRate: 180,
            totalSellRate: 280,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-5',
            expenseItemId: 'EXP-006',
            name: 'Garbage & Marpol Waste Disposal Certificate',
            category: 'PORT_DUES',
            basis: 'Standard garbage certificate',
            quantity: 1,
            unitBuyRate: 390,
            unitSellRate: 520,
            totalBuyRate: 390,
            totalSellRate: 520,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-6',
            expenseItemId: 'EXP-007',
            name: 'Fresh Water Supply (150 MT via barge)',
            category: 'LOGISTICS_SUPPLIES',
            basis: '150 Metric Tons',
            quantity: 150,
            unitBuyRate: 11,
            unitSellRate: 14,
            totalBuyRate: 1650,
            totalSellRate: 2100,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-7',
            expenseItemId: 'EXP-009',
            name: 'Port Agency Attendance Fee',
            category: 'AGENCY_FEE',
            basis: 'Fixed standard rate per call',
            quantity: 1,
            unitBuyRate: 1300,
            unitSellRate: 1750,
            totalBuyRate: 1300,
            totalSellRate: 1750,
            currency: 'USD',
          },
        ],
      },
      pda: {
        quoteNo: 'PDA-2026-0098-FINAL',
        date: '2026-08-28',
        currency: 'USD',
        totalBuyRate: 8550,
        totalSellRate: 11290,
        marginAmount: 2740,
        marginPercentage: 24.27,
        status: 'APPROVED',
        items: [
          {
            id: 'ITM-PDA-1',
            expenseItemId: 'EXP-001',
            name: 'Harbor Pilotage & Tug Services (In & Out)',
            category: 'PILOTAGE_TOWAGE',
            basis: 'Official Pelindo schedule',
            quantity: 2,
            unitBuyRate: 1800,
            unitSellRate: 2350,
            totalBuyRate: 3600,
            totalSellRate: 4700,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-2',
            expenseItemId: 'EXP-002',
            name: 'Wharfage & Berthing Dues (Pelindo Batam)',
            category: 'BERTHING',
            basis: 'Berth 101 quay dues',
            quantity: 4,
            unitBuyRate: 230,
            unitSellRate: 310,
            totalBuyRate: 920,
            totalSellRate: 1240,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-3',
            expenseItemId: 'EXP-003',
            name: 'Line Mooring & Unmooring Gang',
            category: 'BERTHING',
            basis: '2 operations',
            quantity: 2,
            unitBuyRate: 105,
            unitSellRate: 150,
            totalBuyRate: 210,
            totalSellRate: 300,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-4',
            expenseItemId: 'EXP-008',
            name: 'CIQP Formalities & Health Quarantine Clearance',
            category: 'IMMIGRATION_CUSTOMS',
            basis: 'Lump sum vessel call clearance',
            quantity: 1,
            unitBuyRate: 180,
            unitSellRate: 280,
            totalBuyRate: 180,
            totalSellRate: 280,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-5',
            expenseItemId: 'EXP-006',
            name: 'Garbage & Marpol Waste Disposal Certificate',
            category: 'PORT_DUES',
            basis: 'Standard garbage certificate',
            quantity: 1,
            unitBuyRate: 390,
            unitSellRate: 520,
            totalBuyRate: 390,
            totalSellRate: 520,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-6',
            expenseItemId: 'EXP-007',
            name: 'Fresh Water Supply (150 MT via barge)',
            category: 'LOGISTICS_SUPPLIES',
            basis: '150 Metric Tons',
            quantity: 150,
            unitBuyRate: 11,
            unitSellRate: 14,
            totalBuyRate: 1650,
            totalSellRate: 2100,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-7',
            expenseItemId: 'EXP-004',
            name: 'Crew Change Immigration Protocol & OKTB (4 Crew)',
            category: 'CREW_CHANGE',
            basis: '4 crew sign-offs',
            quantity: 4,
            unitBuyRate: 75,
            unitSellRate: 100,
            totalBuyRate: 300,
            totalSellRate: 400,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-8',
            expenseItemId: 'EXP-009',
            name: 'Port Agency Attendance Fee',
            category: 'AGENCY_FEE',
            basis: 'Fixed standard rate per call',
            quantity: 1,
            unitBuyRate: 1300,
            unitSellRate: 1750,
            totalBuyRate: 1300,
            totalSellRate: 1750,
            currency: 'USD',
          },
        ],
      },
      crewChange: {
        id: 'CC-2026-0098',
        date: '2026-09-03',
        signOnCount: 1,
        signOffCount: 3,
        logisticsCost: 350,
        immigrationVisaCost: 280,
        transportCost: 420,
        totalCostUSD: 1050,
        totalCostIDR: 16590000,
        status: 'IN_TRANSIT',
        members: [
          {
            id: 'CRW-01',
            name: 'Rodrigo Dela Cruz',
            passportNumber: 'P8923145B',
            seamanBook: 'SB-PH-9921',
            rank: 'Chief Engineer',
            nationality: 'Philippines',
            type: 'SIGN_OFF',
            flightDetails: 'SQ 953 BTH-SIN -> PR 508 SIN-MNL',
            hotelBooked: true,
            transitCostUSD: 380,
            immigrationStatus: 'CLEARED',
          },
          {
            id: 'CRW-02',
            name: 'Arun Kumar Sharma',
            passportNumber: 'Z3309112',
            seamanBook: 'SB-IN-4421',
            rank: 'Second Officer',
            nationality: 'India',
            type: 'SIGN_OFF',
            flightDetails: 'GA 881 BTH-CGK -> AI 383 DEL',
            hotelBooked: true,
            transitCostUSD: 350,
            immigrationStatus: 'CLEARED',
          },
          {
            id: 'CRW-03',
            name: 'Eduardo Santos',
            passportNumber: 'P7712398C',
            seamanBook: 'SB-PH-8102',
            rank: 'Able Seaman (AB)',
            nationality: 'Philippines',
            type: 'SIGN_OFF',
            flightDetails: 'SQ 953 BTH-SIN -> PR 510 SIN-MNL',
            hotelBooked: true,
            transitCostUSD: 320,
            immigrationStatus: 'CLEARED',
          },
          {
            id: 'CRW-04',
            name: 'Agus Triyono',
            passportNumber: 'A1992834',
            seamanBook: 'SB-ID-11029',
            rank: 'Chief Engineer (Reliever)',
            nationality: 'Indonesia',
            type: 'SIGN_ON',
            hotelBooked: false,
            transitCostUSD: 120,
            immigrationStatus: 'CLEARED',
          },
        ],
      },
    },

    // 3. Manager Approval
    managerApproval: {
      status: 'APPROVED',
      approvedBy: 'Capt. Hendra Pratama (MANAGER_OPS)',
      approvedAt: '2026-08-28T14:30:00Z',
      notes: 'PDA and crew change logistics approved. Buy rates confirmed with Pelindo Batam. Margin of 24.27% conforms to company KPI policy.',
      allowedMarginTolerancePct: 5.0,
    },

    // 4. Operational Data
    operationalData: {
      ata: '2026-09-02T07:45',
      atb: '2026-09-02T11:30',
      atd: '2026-09-05T17:00 (Est.)',
      pilotOnBoardTime: '2026-09-02T09:15',
      pilotOffTime: '2026-09-02T11:45',
      berthZoneName: 'Berth 101 Bulk & General',
      cargoQuantityMetricTons: 42500,
      cargoCommodity: 'Steam Coal in bulk',
      harborMasterClearanceNo: 'KSOP-BTH/SPM/IX/2026/0891',
      statementOfFacts: [
        {
          id: 'SOF-01',
          timestamp: '2026-09-02 07:45',
          event: 'Vessel arrived at Batam pilot boarding ground (Nipa road)',
          remarks: 'Notice of Readiness (NOR) tendered to Charterers and Agent',
        },
        {
          id: 'SOF-02',
          timestamp: '2026-09-02 09:15',
          event: 'Harbor Pilot Capt. Suroso on board with 2 tugboats (TB Batam Jaya 01 & 02)',
        },
        {
          id: 'SOF-03',
          timestamp: '2026-09-02 11:30',
          event: 'All fast alongside Berth 101, Port of Batu Ampar',
          remarks: '6 head lines, 4 stern lines secured',
        },
        {
          id: 'SOF-04',
          timestamp: '2026-09-02 13:00',
          event: 'CIQP inspection completed. Free Pratique granted by Port Health',
        },
        {
          id: 'SOF-05',
          timestamp: '2026-09-02 14:00',
          event: 'Discharge commenced using shore grabs and conveyor system',
        },
        {
          id: 'SOF-06',
          timestamp: '2026-09-03 08:30',
          event: 'Immigration officer cleared 3 sign-off crew and 1 sign-on engineer',
          remarks: 'Crew escorted to Batam center ferry terminal',
        },
      ],
    },

    // 5. Actual Cost (logged by FDA/Ops)
    actualCosts: [
      {
        id: 'ACT-001',
        jobId: 'VC-2026-0098',
        itemCode: 'EXP-001',
        description: 'Pelindo Pilotage & Tug Inward Invoice',
        category: 'PILOTAGE_TOWAGE',
        vendorName: 'PT Pelabuhan Indonesia (Persero) Batam',
        invoiceOrVoucherNo: 'INV-PLND-88912',
        date: '2026-09-02',
        amount: 1780,
        currency: 'USD',
        pdaAmountEstimated: 1800,
        varianceAmount: -20,
        status: 'VERIFIED',
      },
      {
        id: 'ACT-002',
        jobId: 'VC-2026-0098',
        itemCode: 'EXP-003',
        description: 'Mooring Boat Gang in Batam',
        category: 'BERTHING',
        vendorName: 'Batam Line Boat Services',
        invoiceOrVoucherNo: 'VCH-BLB-0412',
        date: '2026-09-02',
        amount: 105,
        currency: 'USD',
        pdaAmountEstimated: 105,
        varianceAmount: 0,
        status: 'VERIFIED',
      },
      {
        id: 'ACT-003',
        jobId: 'VC-2026-0098',
        itemCode: 'EXP-008',
        description: 'Port Health Quarantine CIQP Official Receipt',
        category: 'IMMIGRATION_CUSTOMS',
        vendorName: 'Balai Kekarantinaan Kesehatan Batam',
        invoiceOrVoucherNo: 'PNBP-KESP-9941',
        date: '2026-09-02',
        amount: 175,
        currency: 'USD',
        pdaAmountEstimated: 180,
        varianceAmount: -5,
        status: 'VERIFIED',
      },
      {
        id: 'ACT-004',
        jobId: 'VC-2026-0098',
        itemCode: 'EXP-004',
        description: 'Kantor Imigrasi Sign-off 3 Crew & Visa on Arrival',
        category: 'CREW_CHANGE',
        vendorName: 'Kantor Imigrasi Kelas I TPI Batam',
        invoiceOrVoucherNo: 'PNBP-IMI-33291',
        date: '2026-09-03',
        amount: 290,
        currency: 'USD',
        pdaAmountEstimated: 300,
        varianceAmount: -10,
        status: 'APPROVED_BY_FDA',
      },
      {
        id: 'ACT-005',
        jobId: 'VC-2026-0098',
        itemCode: 'EXP-005',
        description: 'Crew Airport & Fast Ferry Transit Logistics',
        category: 'LOGISTICS_SUPPLIES',
        vendorName: 'Citra Samudra Launch Logistics',
        invoiceOrVoucherNo: 'CSL-LOG-2026-89',
        date: '2026-09-03',
        amount: 380,
        currency: 'USD',
        pdaAmountEstimated: 420,
        varianceAmount: -40,
        status: 'APPROVED_BY_FDA',
      },
    ],

    // 6. FDA (Final Disbursement Account)
    fda: {
      fdaNo: 'FDA-2026-0098',
      date: '2026-09-03',
      totalEstimatedBuy: 8550,
      totalEstimatedSell: 11290,
      totalActualCost: 8390,
      finalBilledToPrincipal: 11290,
      varianceAmount: -160,
      variancePercentage: -1.87,
      fdaApproved: true,
      approvedBy: 'Rizky Kurniawan (FDA)',
      approvedAt: '2026-09-03T09:00:00Z',
      notes: 'Actual expenditures are $160 below PDA budget due to favorable tug duration. Actual cost vouchers matched with receipts.',
    },

    // 7. AP (Accounts Payable)
    ap: [
      {
        id: 'AP-001',
        jobId: 'VC-2026-0098',
        voucherNo: 'APV-2026-0181',
        vendorName: 'PT Pelabuhan Indonesia (Persero)',
        description: 'Pelindo Inward Pilotage & Berth Bill',
        invoiceDate: '2026-09-02',
        dueDate: '2026-09-16',
        amount: 2700,
        currency: 'USD',
        status: 'PARTIALLY_PAID',
        paymentRef: 'BNI-TRF-099231',
        paidDate: '2026-09-02',
      },
      {
        id: 'AP-002',
        jobId: 'VC-2026-0098',
        voucherNo: 'APV-2026-0182',
        vendorName: 'Batam Line Boat Services',
        description: 'Mooring boat linesman gang',
        invoiceDate: '2026-09-02',
        dueDate: '2026-09-09',
        amount: 210,
        currency: 'USD',
        status: 'PAID',
        paymentRef: 'MDR-TRF-44102',
        paidDate: '2026-09-02',
      },
      {
        id: 'AP-003',
        jobId: 'VC-2026-0098',
        voucherNo: 'APV-2026-0183',
        vendorName: 'Citra Samudra Launch Logistics',
        description: 'Crew change airport & ferry transport',
        invoiceDate: '2026-09-03',
        dueDate: '2026-09-17',
        amount: 380,
        currency: 'USD',
        status: 'UNPAID',
      },
    ],

    // 8. AR (Accounts Receivable)
    ar: [
      {
        id: 'AR-001',
        jobId: 'VC-2026-0098',
        referenceNo: 'ADV-REM-2026-004',
        principalName: 'Global Maritime Lines Pte Ltd',
        description: 'PDA Advance 80% remittance for VC-2026-0098',
        requestedAmount: 9000,
        receivedAmount: 9000,
        currency: 'USD',
        receivedDate: '2026-08-30',
        bankAccount: 'Citibank N.A. USD A/C 990-281-01',
        status: 'RECEIVED',
      },
    ],

    // 9. Principal Invoice
    principalInvoice: {
      invoiceNo: 'INV-MP-2026-0098',
      invoiceDate: '2026-09-03',
      dueDate: '2026-09-24',
      totalAmountUSD: 11290,
      totalAmountIDR: 178382000,
      advanceDeductedUSD: 9000,
      advanceDeductedIDR: 142200000,
      balanceDueUSD: 2290,
      balanceDueIDR: 36182000,
      status: 'ISSUED',
      pdfGenerated: true,
    },

    // 10. Closing
    closing: {
      isClosed: false,
      finalGrossMarginUSD: 2900,
      finalGrossMarginIDR: 45820000,
      postVoyageRemarks: 'Pending final vessel departure and collection of balance $2,290 before final closure.',
    },
  },

  // Second Job Call (VC-2026-0099) - Tanker at Balikpapan STS
  {
    jobId: 'VC-2026-0099',
    vesselId: 'VES-002',
    vesselName: 'MT MERDEKA SAMUDRA',
    portId: 'PRT-004',
    portName: 'Semayang / Kariangau, Balikpapan',
    customerId: 'CUST-002',
    customerName: 'Cosco Shipping Energy Transportation',
    currency: 'USD',
    exchangeRateUSDToIDR: 15800,
    eta: '2026-09-07T14:00',
    etd: '2026-09-10T20:00',
    purposeOfCall: 'CARGO_LOADING',
    currentStage: 'MANAGER_APPROVAL',
    status: 'QUOTED',
    createdAt: '2026-08-29T11:20:00Z',
    updatedAt: '2026-09-02T16:00:00Z',

    inquiry: {
      inquiryNo: 'INQ-2026-0189',
      date: '2026-08-29',
      cargoDetails: 'Load 80,000 MT Fuel Oil at Balikpapan STS Point #2',
      estimatedDays: 3,
      specialRequirements: 'Fender boat and STS master attendance required. 2 tugs on standby.',
      status: 'CONVERTED',
      createdBy: 'Sarah Wijaya (SALES)',
    },

    quotation: {
      epda: {
        quoteNo: 'EPDA-2026-0099-IDR-USD',
        date: '2026-08-30',
        currency: 'USD',
        totalBuyRate: 14200,
        totalSellRate: 18500,
        marginAmount: 4300,
        marginPercentage: 23.24,
        status: 'SUBMITTED',
        items: [
          {
            id: 'ITM-EPDA-99-1',
            expenseItemId: 'EXP-001',
            name: 'STS Pilotage & Tanker Escort Tugboat (2 x 5000 HP)',
            category: 'PILOTAGE_TOWAGE',
            basis: 'Tanker 64,200 GRT STS package',
            quantity: 1,
            unitBuyRate: 7500,
            unitSellRate: 9800,
            totalBuyRate: 7500,
            totalSellRate: 9800,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-99-2',
            expenseItemId: 'EXP-005',
            name: 'Yokohama Pneumatic Fendering & Safety Rigging',
            category: 'LOGISTICS_SUPPLIES',
            basis: 'STS transfer setup',
            quantity: 1,
            unitBuyRate: 3500,
            unitSellRate: 4600,
            totalBuyRate: 3500,
            totalSellRate: 4600,
            currency: 'USD',
          },
          {
            id: 'ITM-EPDA-99-3',
            expenseItemId: 'EXP-009',
            name: 'Agency Attendance & STS Documentation Fee',
            category: 'AGENCY_FEE',
            basis: 'Comprehensive tanker attendance',
            quantity: 1,
            unitBuyRate: 3200,
            unitSellRate: 4100,
            totalBuyRate: 3200,
            totalSellRate: 4100,
            currency: 'USD',
          },
        ],
      },
      pda: {
        quoteNo: 'PDA-2026-0099-PROFORMA',
        date: '2026-08-31',
        currency: 'USD',
        totalBuyRate: 14200,
        totalSellRate: 18500,
        marginAmount: 4300,
        marginPercentage: 23.24,
        status: 'SUBMITTED',
        items: [
          {
            id: 'ITM-PDA-99-1',
            expenseItemId: 'EXP-001',
            name: 'STS Pilotage & Tanker Escort Tugboat (2 x 5000 HP)',
            category: 'PILOTAGE_TOWAGE',
            basis: 'Tanker 64,200 GRT STS package',
            quantity: 1,
            unitBuyRate: 7500,
            unitSellRate: 9800,
            totalBuyRate: 7500,
            totalSellRate: 9800,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-99-2',
            expenseItemId: 'EXP-005',
            name: 'Yokohama Pneumatic Fendering & Safety Rigging',
            category: 'LOGISTICS_SUPPLIES',
            basis: 'STS transfer setup',
            quantity: 1,
            unitBuyRate: 3500,
            unitSellRate: 4600,
            totalBuyRate: 3500,
            totalSellRate: 4600,
            currency: 'USD',
          },
          {
            id: 'ITM-PDA-99-3',
            expenseItemId: 'EXP-009',
            name: 'Agency Attendance & STS Documentation Fee',
            category: 'AGENCY_FEE',
            basis: 'Comprehensive tanker attendance',
            quantity: 1,
            unitBuyRate: 3200,
            unitSellRate: 4100,
            totalBuyRate: 3200,
            totalSellRate: 4100,
            currency: 'USD',
          },
        ],
      },
      crewChange: {
        id: 'CC-2026-0099',
        date: '2026-09-08',
        signOnCount: 0,
        signOffCount: 0,
        logisticsCost: 0,
        immigrationVisaCost: 0,
        transportCost: 0,
        totalCostUSD: 0,
        totalCostIDR: 0,
        status: 'PLANNED',
        members: [],
      },
    },

    managerApproval: {
      status: 'PENDING',
      notes: 'Under review by Ops Manager. Checking Pelindo Balikpapan tug reservation confirmation.',
      allowedMarginTolerancePct: 5.0,
    },

    operationalData: {
      statementOfFacts: [],
    },
    actualCosts: [],
    fda: {
      fdaNo: 'FDA-2026-0099',
      date: '2026-09-10',
      totalEstimatedBuy: 14200,
      totalEstimatedSell: 18500,
      totalActualCost: 0,
      finalBilledToPrincipal: 0,
      varianceAmount: 0,
      variancePercentage: 0,
      fdaApproved: false,
    },
    ap: [],
    ar: [],
    principalInvoice: {
      invoiceNo: 'INV-MP-2026-0099',
      invoiceDate: '2026-09-10',
      dueDate: '2026-10-01',
      totalAmountUSD: 18500,
      totalAmountIDR: 292300000,
      advanceDeductedUSD: 0,
      advanceDeductedIDR: 0,
      balanceDueUSD: 18500,
      balanceDueIDR: 292300000,
      status: 'DRAFT',
      pdfGenerated: false,
    },
    closing: {
      isClosed: false,
      finalGrossMarginUSD: 0,
      finalGrossMarginIDR: 0,
    },
  },

  // Third Job Call (VC-2026-0095) - Closed Job for P&L Demonstration
  {
    jobId: 'VC-2026-0095',
    vesselId: 'VES-003',
    vesselName: 'MV PACIFIC HORIZON',
    portId: 'PRT-002',
    portName: 'Tanjung Priok, Jakarta',
    customerId: 'CUST-004',
    customerName: 'A.P. Moller - Maersk Agency',
    currency: 'USD',
    exchangeRateUSDToIDR: 15800,
    eta: '2026-08-15T06:00',
    etd: '2026-08-17T18:00',
    purposeOfCall: 'CARGO_DISCHARGE',
    currentStage: 'CLOSED',
    status: 'CLOSED',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-25T17:00:00Z',

    inquiry: {
      inquiryNo: 'INQ-2026-0170',
      date: '2026-08-10',
      cargoDetails: '1,450 TEU Container discharge at JICT 1',
      estimatedDays: 2.5,
      specialRequirements: 'Fast turn-around requested.',
      status: 'CONVERTED',
      createdBy: 'Sarah Wijaya (SALES)',
    },

    quotation: {
      epda: {
        quoteNo: 'EPDA-2026-0095',
        date: '2026-08-11',
        currency: 'USD',
        totalBuyRate: 6800,
        totalSellRate: 9100,
        marginAmount: 2300,
        marginPercentage: 25.27,
        status: 'APPROVED',
        items: [],
      },
      pda: {
        quoteNo: 'PDA-2026-0095',
        date: '2026-08-12',
        currency: 'USD',
        totalBuyRate: 6800,
        totalSellRate: 9100,
        marginAmount: 2300,
        marginPercentage: 25.27,
        status: 'APPROVED',
        items: [],
      },
      crewChange: {
        id: 'CC-2026-0095',
        date: '2026-08-16',
        signOnCount: 2,
        signOffCount: 2,
        logisticsCost: 200,
        immigrationVisaCost: 150,
        transportCost: 250,
        totalCostUSD: 600,
        totalCostIDR: 9480000,
        status: 'COMPLETED',
        members: [],
      },
    },

    managerApproval: {
      status: 'APPROVED',
      approvedBy: 'Capt. Hendra Pratama (MANAGER_OPS)',
      approvedAt: '2026-08-12T15:00:00Z',
      notes: 'Approved standard container call tariff.',
      allowedMarginTolerancePct: 5.0,
    },

    operationalData: {
      ata: '2026-08-15T05:30',
      atb: '2026-08-15T08:00',
      atd: '2026-08-17T17:45',
      berthZoneName: 'Jakarta International Container Terminal (JICT 1)',
      cargoQuantityMetricTons: 18500,
      cargoCommodity: 'Containerized Cargo 1,450 TEU',
      statementOfFacts: [
        { id: 'SOF-95-1', timestamp: '2026-08-15 05:30', event: 'Vessel arrived Priok Roads' },
        { id: 'SOF-95-2', timestamp: '2026-08-15 08:00', event: 'Berthed JICT 1 starboard side' },
        { id: 'SOF-95-3', timestamp: '2026-08-17 17:45', event: 'Sailed out to Tanjung Pelepas' },
      ],
    },

    actualCosts: [
      {
        id: 'ACT-95-1',
        jobId: 'VC-2026-0095',
        itemCode: 'EXP-001',
        description: 'Pelindo Tanjung Priok In & Out pilot/tug',
        category: 'PILOTAGE_TOWAGE',
        vendorName: 'PT Pelindo Regional 2 Tanjung Priok',
        invoiceOrVoucherNo: 'INV-TPP-0881',
        date: '2026-08-16',
        amount: 3200,
        currency: 'USD',
        pdaAmountEstimated: 3250,
        varianceAmount: -50,
        status: 'APPROVED_BY_FDA',
      },
      {
        id: 'ACT-95-2',
        jobId: 'VC-2026-0095',
        itemCode: 'EXP-002',
        description: 'Wharfage & JICT Quay Dues',
        category: 'BERTHING',
        vendorName: 'PT JICT Tanjung Priok',
        invoiceOrVoucherNo: 'INV-JICT-991',
        date: '2026-08-17',
        amount: 2400,
        currency: 'USD',
        pdaAmountEstimated: 2400,
        varianceAmount: 0,
        status: 'APPROVED_BY_FDA',
      },
      {
        id: 'ACT-95-3',
        jobId: 'VC-2026-0095',
        itemCode: 'EXP-009',
        description: 'Agency attendance cost',
        category: 'AGENCY_FEE',
        vendorName: 'MaritimPort Internal',
        invoiceOrVoucherNo: 'VCH-INT-882',
        date: '2026-08-17',
        amount: 1100,
        currency: 'USD',
        pdaAmountEstimated: 1150,
        varianceAmount: -50,
        status: 'APPROVED_BY_FDA',
      },
    ],

    fda: {
      fdaNo: 'FDA-2026-0095',
      date: '2026-08-19',
      totalEstimatedBuy: 6800,
      totalEstimatedSell: 9100,
      totalActualCost: 6700,
      finalBilledToPrincipal: 9100,
      varianceAmount: -100,
      variancePercentage: -1.47,
      fdaApproved: true,
      approvedBy: 'Rizky Kurniawan (FDA)',
      approvedAt: '2026-08-19T11:00:00Z',
      notes: 'Final Disbursement Account reconciled with zero discrepancies.',
    },

    ap: [
      {
        id: 'AP-95-1',
        jobId: 'VC-2026-0095',
        voucherNo: 'APV-2026-0150',
        vendorName: 'PT Pelindo Regional 2',
        description: 'Full port dues settlement',
        invoiceDate: '2026-08-16',
        dueDate: '2026-08-25',
        amount: 5600,
        currency: 'USD',
        status: 'PAID',
        paymentRef: 'MDR-TRF-088192',
        paidDate: '2026-08-20',
      },
    ],

    ar: [
      {
        id: 'AR-95-1',
        jobId: 'VC-2026-0095',
        referenceNo: 'REM-MAER-0091',
        principalName: 'A.P. Moller - Maersk Agency',
        description: 'Full settlement of Invoice INV-MP-2026-0095',
        requestedAmount: 9100,
        receivedAmount: 9100,
        currency: 'USD',
        receivedDate: '2026-08-24',
        bankAccount: 'Citibank N.A. USD A/C 990-281-01',
        status: 'RECEIVED',
      },
    ],

    principalInvoice: {
      invoiceNo: 'INV-MP-2026-0095',
      invoiceDate: '2026-08-19',
      dueDate: '2026-09-02',
      totalAmountUSD: 9100,
      totalAmountIDR: 143780000,
      advanceDeductedUSD: 7000,
      advanceDeductedIDR: 110600000,
      balanceDueUSD: 0,
      balanceDueIDR: 0,
      status: 'SETTLED',
      pdfGenerated: true,
    },

    closing: {
      isClosed: true,
      closedAt: '2026-08-25T16:45:00Z',
      closedBy: 'Dewi Lestari, SE, Ak (FINANCE)',
      finalGrossMarginUSD: 2400,
      finalGrossMarginIDR: 37920000,
      postVoyageRemarks: 'Job successfully audited and closed. All vendor AP vouchers paid in full, and Principal remittance received with 100% balance cleared.',
    },
  },
];
