ALTER TABLE vessel_calls
  MODIFY COLUMN purpose_of_call ENUM(
    'CARGO_DISCHARGE',
    'CARGO_LOADING',
    'CARGO_OPERATIONS',
    'SHIP_SERVICES_SUPPLIES',
    'CREW_PASSENGER_OPERATIONS',
    'TECHNICAL_EMERGENCY',
    'PORT_SERVICE',
    'HUSBANDRY_SERVICES',
    'VESSEL_SUPPLIES',
    'MAINTENANCE_WASTE_MANAGEMENT',
    'ADMINISTRATIVE_SERVICES',
    'BUNKERING',
    'CREW_CHANGE_ONLY',
    'REPAIR_MAINTENANCE'
  ) NOT NULL;